# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Activate Mozilla
email: participation@mozilla.com
description: > # this means to ignore newlines until "baseurl:"
    Get involved with the focus initiatives at Mozilla
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: mozparticipate
github_username:  mozilla

# Build settings
markdown: kramdown

include: ['_pages']
exclude: ['locales']

gems:
  - jekyll-redirect-from
